/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountEditDialog: typeof import('./manager/components/AccountEditDialog.vue')['default']
    AccountManager: typeof import('./manager/components/AccountManager.vue')['default']
    AddCustomForm: typeof import('./manager/components/AddCustomForm.vue')['default']
    CustomForm: typeof import('./manager/components/CustomForm.vue')['default']
    ElementItem: typeof import('./search/components/ElementsTab/ElementItem.vue')['default']
    ElementsTab: typeof import('./search/components/ElementsTab.vue')['default']
    HelloWorld: typeof import('./search/components/HelloWorld.vue')['default']
    ManagerTool: typeof import('./manager/components/ManagerTool.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NDivider: typeof import('naive-ui')['NDivider']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    NUpload: typeof import('naive-ui')['NUpload']
    RoleEditDialog: typeof import('./manager/components/RoleEditDialog.vue')['default']
    RoleManager: typeof import('./manager/components/RoleManager.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchResultList: typeof import('./search/components/SearchResultList.vue')['default']
    UserEditDialog: typeof import('./manager/components/UserEditDialog.vue')['default']
    UserManager: typeof import('./manager/components/UserManager.vue')['default']
  }
}
